from app.extensions import db
from app.models.city_model import City
from app.models.state_model import State

def seed_cities():
    if City.query.count() > 0:
        print("Cities already seeded.")
        return

    cities = [
        {"city_code": "CIT-001", "name": "Maroa", "state_code": "ST-001", "is_capital": False},
        {"city_code": "CIT-002", "name": "Puerto Ayacucho", "state_code": "ST-001", "is_capital": True},
        {"city_code": "CIT-003", "name": "San Fernando de Atabapo", "state_code": "ST-001", "is_capital": False},
        {"city_code": "CIT-004", "name": "Anaco", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-005", "name": "Aragua de Barcelona", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-006", "name": "Barcelona", "state_code": "ST-002", "is_capital": True},
        {"city_code": "CIT-007", "name": "Boca de Uchire", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-008", "name": "Cantaura", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-009", "name": "Clarines", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-010", "name": "El Chaparro", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-011", "name": "El Pao Anzoátegui", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-012", "name": "El Tigre", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-013", "name": "El Tigrito", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-014", "name": "Guanape", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-015", "name": "Guanta", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-016", "name": "Lechería", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-017", "name": "Onoto", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-018", "name": "Pariaguán", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-019", "name": "Píritu", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-020", "name": "Puerto La Cruz", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-021", "name": "Puerto Píritu", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-022", "name": "Sabana de Uchire", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-023", "name": "San Mateo Anzoátegui", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-024", "name": "San Pablo Anzoátegui", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-025", "name": "San Tomé", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-026", "name": "Santa Ana de Anzoátegui", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-027", "name": "Santa Fe Anzoátegui", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-028", "name": "Santa Rosa", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-029", "name": "Soledad", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-030", "name": "Urica", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-031", "name": "Valle de Guanape", "state_code": "ST-002", "is_capital": False},
        {"city_code": "CIT-043", "name": "Achaguas", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-044", "name": "Biruaca", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-045", "name": "Bruzual", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-046", "name": "El Amparo", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-047", "name": "El Nula", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-048", "name": "Elorza", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-049", "name": "Guasdualito", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-050", "name": "Mantecal", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-051", "name": "Puerto Páez", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-052", "name": "San Fernando de Apure", "state_code": "ST-003", "is_capital": True},
        {"city_code": "CIT-053", "name": "San Juan de Payara", "state_code": "ST-003", "is_capital": False},
        {"city_code": "CIT-054", "name": "Barbacoas", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-055", "name": "Cagua", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-056", "name": "Camatagua", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-058", "name": "Choroní", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-059", "name": "Colonia Tovar", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-060", "name": "El Consejo", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-061", "name": "La Victoria", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-062", "name": "Las Tejerías", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-063", "name": "Magdaleno", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-064", "name": "Maracay", "state_code": "ST-004", "is_capital": True},
        {"city_code": "CIT-065", "name": "Ocumare de La Costa", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-066", "name": "Palo Negro", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-067", "name": "San Casimiro", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-068", "name": "San Mateo", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-069", "name": "San Sebastián", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-070", "name": "Santa Cruz de Aragua", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-071", "name": "Tocorón", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-072", "name": "Turmero", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-073", "name": "Villa de Cura", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-074", "name": "Zuata", "state_code": "ST-004", "is_capital": False},
        {"city_code": "CIT-075", "name": "Barinas", "state_code": "ST-005", "is_capital": True},
        {"city_code": "CIT-076", "name": "Barinitas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-077", "name": "Barrancas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-078", "name": "Calderas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-079", "name": "Capitanejo", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-080", "name": "Ciudad Bolivia", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-081", "name": "El Cantón", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-082", "name": "Las Veguitas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-083", "name": "Libertad de Barinas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-084", "name": "Sabaneta", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-085", "name": "Santa Bárbara de Barinas", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-086", "name": "Socopó", "state_code": "ST-005", "is_capital": False},
        {"city_code": "CIT-087", "name": "Caicara del Orinoco", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-088", "name": "Canaima", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-089", "name": "Ciudad Bolívar", "state_code": "ST-006", "is_capital": True},
        {"city_code": "CIT-090", "name": "Ciudad Piar", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-091", "name": "El Callao", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-092", "name": "El Dorado", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-093", "name": "El Manteco", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-094", "name": "El Palmar", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-095", "name": "El Pao", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-096", "name": "Guasipati", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-097", "name": "Guri", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-098", "name": "La Paragua", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-099", "name": "Matanzas", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-100", "name": "Puerto Ordaz", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-101", "name": "San Félix", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-102", "name": "Santa Elena de Uairén", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-103", "name": "Tumeremo", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-104", "name": "Unare", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-105", "name": "Upata", "state_code": "ST-006", "is_capital": False},
        {"city_code": "CIT-106", "name": "Bejuma", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-107", "name": "Belén", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-108", "name": "Campo de Carabobo", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-109", "name": "Canoabo", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-110", "name": "Central Tacarigua", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-111", "name": "Chirgua", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-112", "name": "Ciudad Alianza", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-113", "name": "El Palito", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-114", "name": "Guacara", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-115", "name": "Guigue", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-116", "name": "Las Trincheras", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-117", "name": "Los Guayos", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-118", "name": "Mariara", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-119", "name": "Miranda", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-120", "name": "Montalbán", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-121", "name": "Morón", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-122", "name": "Naguanagua", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-123", "name": "Puerto Cabello", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-124", "name": "San Joaquín", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-125", "name": "Tocuyito", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-126", "name": "Urama", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-127", "name": "Valencia", "state_code": "ST-007", "is_capital": True},
        {"city_code": "CIT-128", "name": "Vigirimita", "state_code": "ST-007", "is_capital": False},
        {"city_code": "CIT-129", "name": "Aguirre", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-130", "name": "Apartaderos Cojedes", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-131", "name": "Arismendi", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-132", "name": "Camuriquito", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-133", "name": "El Baúl", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-134", "name": "El Limón", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-135", "name": "El Pao Cojedes", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-136", "name": "El Socorro", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-137", "name": "La Aguadita", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-138", "name": "Las Vegas", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-139", "name": "Libertad de Cojedes", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-140", "name": "Mapuey", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-141", "name": "Piñedo", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-142", "name": "Samancito", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-143", "name": "San Carlos", "state_code": "ST-008", "is_capital": True},
        {"city_code": "CIT-144", "name": "Sucre", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-145", "name": "Tinaco", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-146", "name": "Tinaquillo", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-147", "name": "Vallecito", "state_code": "ST-008", "is_capital": False},
        {"city_code": "CIT-148", "name": "Tucupita", "state_code": "ST-009", "is_capital": True},
        {"city_code": "CIT-149", "name": "Caracas", "state_code": "ST-024", "is_capital": True},
        {"city_code": "CIT-150", "name": "El Junquito", "state_code": "ST-024", "is_capital": False},
        {"city_code": "CIT-151", "name": "Adícora", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-152", "name": "Boca de Aroa", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-153", "name": "Cabure", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-154", "name": "Capadare", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-155", "name": "Capatárida", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-156", "name": "Chichiriviche", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-157", "name": "Churuguara", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-158", "name": "Coro", "state_code": "ST-010", "is_capital": True},
        {"city_code": "CIT-159", "name": "Cumarebo", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-160", "name": "Dabajuro", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-161", "name": "Judibana", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-162", "name": "La Cruz de Taratara", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-163", "name": "La Vela de Coro", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-164", "name": "Los Taques", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-165", "name": "Maparari", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-166", "name": "Mene de Mauroa", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-167", "name": "Mirimire", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-168", "name": "Pedregal", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-169", "name": "Píritu Falcón", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-170", "name": "Pueblo Nuevo Falcón", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-171", "name": "Puerto Cumarebo", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-172", "name": "Punta Cardón", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-173", "name": "Punto Fijo", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-174", "name": "San Juan de Los Cayos", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-175", "name": "San Luis", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-176", "name": "Santa Ana Falcón", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-177", "name": "Santa Cruz De Bucaral", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-178", "name": "Tocopero", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-179", "name": "Tocuyo de La Costa", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-180", "name": "Tucacas", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-181", "name": "Yaracal", "state_code": "ST-010", "is_capital": False},
        {"city_code": "CIT-182", "name": "Altagracia de Orituco", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-183", "name": "Cabruta", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-184", "name": "Calabozo", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-185", "name": "Camaguán", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-196", "name": "Chaguaramas Guárico", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-197", "name": "El Socorro", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-198", "name": "El Sombrero", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-199", "name": "Las Mercedes de Los Llanos", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-200", "name": "Lezama", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-201", "name": "Onoto", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-202", "name": "Ortíz", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-203", "name": "San José de Guaribe", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-204", "name": "San Juan de Los Morros", "state_code": "ST-011", "is_capital": True},
        {"city_code": "CIT-205", "name": "San Rafael de Laya", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-206", "name": "Santa María de Ipire", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-207", "name": "Tucupido", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-208", "name": "Valle de La Pascua", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-209", "name": "Zaraza", "state_code": "ST-011", "is_capital": False},
        {"city_code": "CIT-210", "name": "Aguada Grande", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-211", "name": "Atarigua", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-212", "name": "Barquisimeto", "state_code": "ST-012", "is_capital": True},
        {"city_code": "CIT-213", "name": "Bobare", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-214", "name": "Cabudare", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-215", "name": "Carora", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-216", "name": "Cubiro", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-217", "name": "Cují", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-218", "name": "Duaca", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-219", "name": "El Manzano", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-220", "name": "El Tocuyo", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-221", "name": "Guaríco", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-222", "name": "Humocaro Alto", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-223", "name": "Humocaro Bajo", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-224", "name": "La Miel", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-225", "name": "Moroturo", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-226", "name": "Quíbor", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-227", "name": "Río Claro", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-228", "name": "Sanare", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-229", "name": "Santa Inés", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-230", "name": "Sarare", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-231", "name": "Siquisique", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-232", "name": "Tintorero", "state_code": "ST-012", "is_capital": False},
        {"city_code": "CIT-233", "name": "Apartaderos Mérida", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-234", "name": "Arapuey", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-235", "name": "Bailadores", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-236", "name": "Caja Seca", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-237", "name": "Canaguá", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-238", "name": "Chachopo", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-239", "name": "Chiguara", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-240", "name": "Ejido", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-241", "name": "El Vigía", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-242", "name": "La Azulita", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-243", "name": "La Playa", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-244", "name": "Lagunillas Mérida", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-245", "name": "Mérida", "state_code": "ST-013", "is_capital": True},
        {"city_code": "CIT-246", "name": "Mesa de Bolívar", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-247", "name": "Mucuchíes", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-248", "name": "Mucujepe", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-249", "name": "Mucuruba", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-250", "name": "Nueva Bolivia", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-251", "name": "Palmarito", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-252", "name": "Pueblo Llano", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-253", "name": "Santa Cruz de Mora", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-254", "name": "Santa Elena de Arenales", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-255", "name": "Santo Domingo", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-256", "name": "Tabáy", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-257", "name": "Timotes", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-258", "name": "Torondoy", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-259", "name": "Tovar", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-260", "name": "Tucani", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-261", "name": "Zea", "state_code": "ST-013", "is_capital": False},
        {"city_code": "CIT-262", "name": "Araguita", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-263", "name": "Carrizal", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-264", "name": "Caucagua", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-265", "name": "Chaguaramas Miranda", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-266", "name": "Charallave", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-267", "name": "Chirimena", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-268", "name": "Chuspa", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-269", "name": "Cúa", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-270", "name": "Cupira", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-271", "name": "Curiepe", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-272", "name": "El Guapo", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-273", "name": "El Jarillo", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-274", "name": "Filas de Mariche", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-275", "name": "Guarenas", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-276", "name": "Guatire", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-277", "name": "Higuerote", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-278", "name": "Los Anaucos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-279", "name": "Los Teques", "state_code": "ST-014", "is_capital": True},
        {"city_code": "CIT-280", "name": "Ocumare del Tuy", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-281", "name": "Panaquire", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-282", "name": "Paracotos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-283", "name": "Río Chico", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-284", "name": "San Antonio de Los Altos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-285", "name": "San Diego de Los Altos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-286", "name": "San Fernando del Guapo", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-287", "name": "San Francisco de Yare", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-288", "name": "San José de Los Altos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-289", "name": "San José de Río Chico", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-290", "name": "San Pedro de Los Altos", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-291", "name": "Santa Lucía", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-292", "name": "Santa Teresa", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-293", "name": "Tacarigua de La Laguna", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-294", "name": "Tacarigua de Mamporal", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-295", "name": "Tácata", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-296", "name": "Turumo", "state_code": "ST-014", "is_capital": False},
        {"city_code": "CIT-297", "name": "Aguasay", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-298", "name": "Aragua de Maturín", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-299", "name": "Barrancas del Orinoco", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-300", "name": "Caicara de Maturín", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-301", "name": "Caripe", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-302", "name": "Caripito", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-303", "name": "Chaguaramal", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-305", "name": "Chaguaramas Monagas", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-307", "name": "El Furrial", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-308", "name": "El Tejero", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-309", "name": "Jusepín", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-310", "name": "La Toscana", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-311", "name": "Maturín", "state_code": "ST-015", "is_capital": True},
        {"city_code": "CIT-312", "name": "Miraflores", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-313", "name": "Punta de Mata", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-314", "name": "Quiriquire", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-315", "name": "San Antonio de Maturín", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-316", "name": "San Vicente Monagas", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-317", "name": "Santa Bárbara", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-318", "name": "Temblador", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-319", "name": "Teresen", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-320", "name": "Uracoa", "state_code": "ST-015", "is_capital": False},
        {"city_code": "CIT-321", "name": "Altagracia", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-322", "name": "Boca de Pozo", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-323", "name": "Boca de Río", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-324", "name": "El Espinal", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-325", "name": "El Valle del Espíritu Santo", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-326", "name": "El Yaque", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-327", "name": "Juangriego", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-328", "name": "La Asunción", "state_code": "ST-016", "is_capital": True},
        {"city_code": "CIT-329", "name": "La Guardia", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-330", "name": "Pampatar", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-331", "name": "Porlamar", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-332", "name": "Puerto Fermín", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-333", "name": "Punta de Piedras", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-334", "name": "San Francisco de Macanao", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-335", "name": "San Juan Bautista", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-336", "name": "San Pedro de Coche", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-337", "name": "Santa Ana de Nueva Esparta", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-338", "name": "Villa Rosa", "state_code": "ST-016", "is_capital": False},
        {"city_code": "CIT-339", "name": "Acarigua", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-340", "name": "Agua Blanca", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-341", "name": "Araure", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-342", "name": "Biscucuy", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-343", "name": "Boconoito", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-344", "name": "Campo Elías", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-345", "name": "Chabasquén", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-346", "name": "Guanare", "state_code": "ST-017", "is_capital": True},
        {"city_code": "CIT-347", "name": "Guanarito", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-348", "name": "La Aparición", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-349", "name": "La Misión", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-350", "name": "Mesa de Cavacas", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-351", "name": "Ospino", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-352", "name": "Papelón", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-353", "name": "Payara", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-354", "name": "Pimpinela", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-355", "name": "Píritu de Portuguesa", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-356", "name": "San Rafael de Onoto", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-357", "name": "Santa Rosalía", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-358", "name": "Turén", "state_code": "ST-017", "is_capital": False},
        {"city_code": "CIT-359", "name": "Altos de Sucre", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-360", "name": "Araya", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-361", "name": "Cariaco", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-362", "name": "Carúpano", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-363", "name": "Casanay", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-364", "name": "Cumaná", "state_code": "ST-018", "is_capital": True},
        {"city_code": "CIT-365", "name": "Cumanacoa", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-366", "name": "El Morro Puerto Santo", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-367", "name": "El Pilar", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-368", "name": "El Poblado", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-369", "name": "Guaca", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-370", "name": "Guiria", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-371", "name": "Irapa", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-372", "name": "Manicuare", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-373", "name": "Mariguitar", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-374", "name": "Río Caribe", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-375", "name": "San Antonio del Golfo", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-376", "name": "San José de Aerocuar", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-377", "name": "San Vicente de Sucre", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-378", "name": "Santa Fe de Sucre", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-379", "name": "Tunapuy", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-380", "name": "Yaguaraparo", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-381", "name": "Yoco", "state_code": "ST-018", "is_capital": False},
        {"city_code": "CIT-382", "name": "Abejales", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-383", "name": "Borota", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-384", "name": "Bramon", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-385", "name": "Capacho", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-386", "name": "Colón", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-387", "name": "Coloncito", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-388", "name": "Cordero", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-389", "name": "El Cobre", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-390", "name": "El Pinal", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-391", "name": "Independencia", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-392", "name": "La Fría", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-393", "name": "La Grita", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-394", "name": "La Pedrera", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-395", "name": "La Tendida", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-396", "name": "Las Delicias", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-397", "name": "Las Hernández", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-398", "name": "Lobatera", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-399", "name": "Michelena", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-400", "name": "Palmira", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-401", "name": "Pregonero", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-402", "name": "Queniquea", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-403", "name": "Rubio", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-404", "name": "San Antonio del Tachira", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-405", "name": "San Cristobal", "state_code": "ST-019", "is_capital": True},
        {"city_code": "CIT-406", "name": "San José de Bolívar", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-407", "name": "San Josecito", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-408", "name": "San Pedro del Río", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-409", "name": "Santa Ana Táchira", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-410", "name": "Seboruco", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-411", "name": "Táriba", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-412", "name": "Umuquena", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-413", "name": "Ureña", "state_code": "ST-019", "is_capital": False},
        {"city_code": "CIT-414", "name": "Batatal", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-415", "name": "Betijoque", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-416", "name": "Boconó", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-417", "name": "Carache", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-418", "name": "Chejende", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-419", "name": "Cuicas", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-420", "name": "El Dividive", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-421", "name": "El Jaguito", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-422", "name": "Escuque", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-423", "name": "Isnotú", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-424", "name": "Jajó", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-425", "name": "La Ceiba", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-426", "name": "La Concepción de Trujllo", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-427", "name": "La Mesa de Esnujaque", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-428", "name": "La Puerta", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-429", "name": "La Quebrada", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-430", "name": "Mendoza Fría", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-431", "name": "Meseta de Chimpire", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-432", "name": "Monay", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-433", "name": "Motatán", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-434", "name": "Pampán", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-435", "name": "Pampanito", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-436", "name": "Sabana de Mendoza", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-437", "name": "San Lázaro", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-438", "name": "Santa Ana de Trujillo", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-439", "name": "Tostós", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-440", "name": "Trujillo", "state_code": "ST-020", "is_capital": True},
        {"city_code": "CIT-441", "name": "Valera", "state_code": "ST-020", "is_capital": False},
        {"city_code": "CIT-442", "name": "Carayaca", "state_code": "ST-021", "is_capital": False},
        {"city_code": "CIT-443", "name": "Litoral", "state_code": "ST-021", "is_capital": False},
        {"city_code": "CIT-444", "name": "Archipiélago Los Roques", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-445", "name": "Aroa", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-446", "name": "Boraure", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-447", "name": "Campo Elías de Yaracuy", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-448", "name": "Chivacoa", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-449", "name": "Cocorote", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-450", "name": "Farriar", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-451", "name": "Guama", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-452", "name": "Marín", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-453", "name": "Nirgua", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-454", "name": "Sabana de Parra", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-455", "name": "Salom", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-456", "name": "San Felipe", "state_code": "ST-022", "is_capital": True},
        {"city_code": "CIT-457", "name": "San Pablo de Yaracuy", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-458", "name": "Urachiche", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-459", "name": "Yaritagua", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-460", "name": "Yumare", "state_code": "ST-022", "is_capital": False},
        {"city_code": "CIT-461", "name": "Bachaquero", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-462", "name": "Bobures", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-463", "name": "Cabimas", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-464", "name": "Campo Concepción", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-465", "name": "Campo Mara", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-466", "name": "Campo Rojo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-467", "name": "Carrasquero", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-468", "name": "Casigua", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-469", "name": "Chiquinquirá", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-470", "name": "Ciudad Ojeda", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-471", "name": "El Batey", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-472", "name": "El Carmelo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-473", "name": "El Chivo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-474", "name": "El Guayabo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-475", "name": "El Mene", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-476", "name": "El Venado", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-477", "name": "Encontrados", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-478", "name": "Gibraltar", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-479", "name": "Isla de Toas", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-480", "name": "La Concepción del Zulia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-481", "name": "La Paz", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-482", "name": "La Sierrita", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-483", "name": "Lagunillas del Zulia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-484", "name": "Las Piedras de Perijá", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-485", "name": "Los Cortijos", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-486", "name": "Machiques", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-487", "name": "Maracaibo", "state_code": "ST-023", "is_capital": True},
        {"city_code": "CIT-488", "name": "Mene Grande", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-489", "name": "Palmarejo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-490", "name": "Paraguaipoa", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-491", "name": "Potrerito", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-492", "name": "Pueblo Nuevo del Zulia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-493", "name": "Puertos de Altagracia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-494", "name": "Punta Gorda", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-495", "name": "Sabaneta de Palma", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-496", "name": "San Francisco", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-497", "name": "San José de Perijá", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-498", "name": "San Rafael del Moján", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-499", "name": "San Timoteo", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-500", "name": "Santa Bárbara Del Zulia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-501", "name": "Santa Cruz de Mara", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-502", "name": "Santa Cruz del Zulia", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-503", "name": "Santa Rita", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-504", "name": "Sinamaica", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-505", "name": "Tamare", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-506", "name": "Tía Juana", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-507", "name": "Villa del Rosario", "state_code": "ST-023", "is_capital": False},
        {"city_code": "CIT-508", "name": "La Guaira", "state_code": "ST-021", "is_capital": True},
        {"city_code": "CIT-509", "name": "Catia La Mar", "state_code": "ST-021", "is_capital": False},
        {"city_code": "CIT-510", "name": "Macuto", "state_code": "ST-021", "is_capital": False},
        {"city_code": "CIT-511", "name": "Naiguatá", "state_code": "ST-021", "is_capital": False},
        {"city_code": "CIT-512", "name": "Archipiélago Los Monjes", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-513", "name": "Isla La Tortuga y Cayos adyacentes", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-514", "name": "Isla La Sola", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-515", "name": "Islas Los Testigos", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-516", "name": "Islas Los Frailes", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-517", "name": "Isla La Orchila", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-518", "name": "Archipiélago Las Aves", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-519", "name": "Isla de Aves", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-520", "name": "Isla La Blanquilla", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-521", "name": "Isla de Patos", "state_code": "ST-025", "is_capital": False},
        {"city_code": "CIT-522", "name": "Islas Los Hermanos", "state_code": "ST-025", "is_capital": False},
    ]

    for data in cities:
        state_code = data.pop("state_code")
        state = State.query.filter_by(state_code=state_code).first()
        
        if not state:
            print(f"Error: No se encontró State con code '{state_code}'. Ejecuta seed_states primero.")
            return

        data["state_id"] = state.id
        city = City(**data)
        db.session.add(city)
    
    db.session.commit()
    print("Cities seeded successfully.")