from app.extensions import db
from app.models.municipality_model import Municipality
from app.models.state_model import State

def seed_municipalities():
    if Municipality.query.count() > 0:
        print("Municipalities already seeded.")
        return

    municipalities = [
        {"municipality_code": "MUN-001", "name": "Alto Orinoco", "state_code": "ST-001"},
        {"municipality_code": "MUN-002", "name": "Atabapo", "state_code": "ST-001"},
        {"municipality_code": "MUN-003", "name": "Atures", "state_code": "ST-001"},
        {"municipality_code": "MUN-004", "name": "Autana", "state_code": "ST-001"},
        {"municipality_code": "MUN-005", "name": "Manapiare", "state_code": "ST-001"},
        {"municipality_code": "MUN-006", "name": "Maroa", "state_code": "ST-001"},
        {"municipality_code": "MUN-007", "name": "Río Negro", "state_code": "ST-001"},
        {"municipality_code": "MUN-008", "name": "Anaco", "state_code": "ST-002"},
        {"municipality_code": "MUN-009", "name": "Aragua", "state_code": "ST-002"},
        {"municipality_code": "MUN-010", "name": "Manuel Ezequiel Bruzual", "state_code": "ST-002"},
        {"municipality_code": "MUN-011", "name": "Diego Bautista Urbaneja", "state_code": "ST-002"},
        {"municipality_code": "MUN-012", "name": "Fernando Peñalver", "state_code": "ST-002"},
        {"municipality_code": "MUN-013", "name": "Francisco Del Carmen Carvajal", "state_code": "ST-002"},
        {"municipality_code": "MUN-014", "name": "General Sir Arthur McGregor", "state_code": "ST-002"},
        {"municipality_code": "MUN-015", "name": "Guanta", "state_code": "ST-002"},
        {"municipality_code": "MUN-016", "name": "Independencia", "state_code": "ST-002"},
        {"municipality_code": "MUN-017", "name": "José Gregorio Monagas", "state_code": "ST-002"},
        {"municipality_code": "MUN-018", "name": "Juan Antonio Sotillo", "state_code": "ST-002"},
        {"municipality_code": "MUN-019", "name": "Juan Manuel Cajigal", "state_code": "ST-002"},
        {"municipality_code": "MUN-020", "name": "Libertad", "state_code": "ST-002"},
        {"municipality_code": "MUN-021", "name": "Francisco de Miranda", "state_code": "ST-002"},
        {"municipality_code": "MUN-022", "name": "Pedro María Freites", "state_code": "ST-002"},
        {"municipality_code": "MUN-023", "name": "Píritu", "state_code": "ST-002"},
        {"municipality_code": "MUN-024", "name": "San José de Guanipa", "state_code": "ST-002"},
        {"municipality_code": "MUN-025", "name": "San Juan de Capistrano", "state_code": "ST-002"},
        {"municipality_code": "MUN-026", "name": "Santa Ana", "state_code": "ST-002"},
        {"municipality_code": "MUN-027", "name": "Simón Bolívar", "state_code": "ST-002"},
        {"municipality_code": "MUN-028", "name": "Simón Rodríguez", "state_code": "ST-002"},
        {"municipality_code": "MUN-029", "name": "Achaguas", "state_code": "ST-003"},
        {"municipality_code": "MUN-030", "name": "Biruaca", "state_code": "ST-003"},
        {"municipality_code": "MUN-031", "name": "Muñóz", "state_code": "ST-003"},
        {"municipality_code": "MUN-032", "name": "Páez", "state_code": "ST-003"},
        {"municipality_code": "MUN-033", "name": "Pedro Camejo", "state_code": "ST-003"},
        {"municipality_code": "MUN-034", "name": "Rómulo Gallegos", "state_code": "ST-003"},
        {"municipality_code": "MUN-035", "name": "San Fernando", "state_code": "ST-003"},
        {"municipality_code": "MUN-036", "name": "Atanasio Girardot", "state_code": "ST-004"},
        {"municipality_code": "MUN-037", "name": "Bolívar", "state_code": "ST-004"},
        {"municipality_code": "MUN-038", "name": "Camatagua", "state_code": "ST-004"},
        {"municipality_code": "MUN-039", "name": "Francisco Linares Alcántara", "state_code": "ST-004"},
        {"municipality_code": "MUN-040", "name": "José Ángel Lamas", "state_code": "ST-004"},
        {"municipality_code": "MUN-041", "name": "José Félix Ribas", "state_code": "ST-004"},
        {"municipality_code": "MUN-042", "name": "José Rafael Revenga", "state_code": "ST-004"},
        {"municipality_code": "MUN-043", "name": "Libertador", "state_code": "ST-004"},
        {"municipality_code": "MUN-044", "name": "Mario Briceño Iragorry", "state_code": "ST-004"},
        {"municipality_code": "MUN-045", "name": "Ocumare de la Costa de Oro", "state_code": "ST-004"},
        {"municipality_code": "MUN-046", "name": "San Casimiro", "state_code": "ST-004"},
        {"municipality_code": "MUN-047", "name": "San Sebastián", "state_code": "ST-004"},
        {"municipality_code": "MUN-048", "name": "Santiago Mariño", "state_code": "ST-004"},
        {"municipality_code": "MUN-049", "name": "Santos Michelena", "state_code": "ST-004"},
        {"municipality_code": "MUN-050", "name": "Sucre", "state_code": "ST-004"},
        {"municipality_code": "MUN-051", "name": "Tovar", "state_code": "ST-004"},
        {"municipality_code": "MUN-052", "name": "Urdaneta", "state_code": "ST-004"},
        {"municipality_code": "MUN-053", "name": "Zamora", "state_code": "ST-004"},
        {"municipality_code": "MUN-054", "name": "Alberto Arvelo Torrealba", "state_code": "ST-005"},
        {"municipality_code": "MUN-055", "name": "Andrés Eloy Blanco", "state_code": "ST-005"},
        {"municipality_code": "MUN-056", "name": "Antonio José de Sucre", "state_code": "ST-005"},
        {"municipality_code": "MUN-057", "name": "Arismendi", "state_code": "ST-005"},
        {"municipality_code": "MUN-058", "name": "Barinas", "state_code": "ST-005"},
        {"municipality_code": "MUN-059", "name": "Bolívar", "state_code": "ST-005"},
        {"municipality_code": "MUN-060", "name": "Cruz Paredes", "state_code": "ST-005"},
        {"municipality_code": "MUN-061", "name": "Ezequiel Zamora", "state_code": "ST-005"},
        {"municipality_code": "MUN-062", "name": "Obispos", "state_code": "ST-005"},
        {"municipality_code": "MUN-063", "name": "Pedraza", "state_code": "ST-005"},
        {"municipality_code": "MUN-064", "name": "Rojas", "state_code": "ST-005"},
        {"municipality_code": "MUN-065", "name": "Sosa", "state_code": "ST-005"},
        {"municipality_code": "MUN-066", "name": "Caroní", "state_code": "ST-006"},
        {"municipality_code": "MUN-067", "name": "Cedeño", "state_code": "ST-006"},
        {"municipality_code": "MUN-068", "name": "El Callao", "state_code": "ST-006"},
        {"municipality_code": "MUN-069", "name": "Gran Sabana", "state_code": "ST-006"},
        {"municipality_code": "MUN-070", "name": "Heres", "state_code": "ST-006"},
        {"municipality_code": "MUN-071", "name": "Piar", "state_code": "ST-006"},
        {"municipality_code": "MUN-072", "name": "Angostura (Raúl Leoni)", "state_code": "ST-006"},
        {"municipality_code": "MUN-073", "name": "Roscio", "state_code": "ST-006"},
        {"municipality_code": "MUN-074", "name": "Sifontes", "state_code": "ST-006"},
        {"municipality_code": "MUN-075", "name": "Sucre", "state_code": "ST-006"},
        {"municipality_code": "MUN-076", "name": "Padre Pedro Chien", "state_code": "ST-006"},
        {"municipality_code": "MUN-077", "name": "Bejuma", "state_code": "ST-007"},
        {"municipality_code": "MUN-078", "name": "Carlos Arvelo", "state_code": "ST-007"},
        {"municipality_code": "MUN-079", "name": "Diego Ibarra", "state_code": "ST-007"},
        {"municipality_code": "MUN-080", "name": "Guacara", "state_code": "ST-007"},
        {"municipality_code": "MUN-081", "name": "Juan José Mora", "state_code": "ST-007"},
        {"municipality_code": "MUN-082", "name": "Libertador", "state_code": "ST-007"},
        {"municipality_code": "MUN-083", "name": "Los Guayos", "state_code": "ST-007"},
        {"municipality_code": "MUN-084", "name": "Miranda", "state_code": "ST-007"},
        {"municipality_code": "MUN-085", "name": "Montalbán", "state_code": "ST-007"},
        {"municipality_code": "MUN-086", "name": "Naguanagua", "state_code": "ST-007"},
        {"municipality_code": "MUN-087", "name": "Puerto Cabello", "state_code": "ST-007"},
        {"municipality_code": "MUN-088", "name": "San Diego", "state_code": "ST-007"},
        {"municipality_code": "MUN-089", "name": "San Joaquín", "state_code": "ST-007"},
        {"municipality_code": "MUN-090", "name": "Valencia", "state_code": "ST-007"},
        {"municipality_code": "MUN-091", "name": "Anzoátegui", "state_code": "ST-008"},
        {"municipality_code": "MUN-092", "name": "Tinaquillo", "state_code": "ST-008"},
        {"municipality_code": "MUN-093", "name": "Girardot", "state_code": "ST-008"},
        {"municipality_code": "MUN-094", "name": "Lima Blanco", "state_code": "ST-008"},
        {"municipality_code": "MUN-095", "name": "Pao de San Juan Bautista", "state_code": "ST-008"},
        {"municipality_code": "MUN-096", "name": "Ricaurte", "state_code": "ST-008"},
        {"municipality_code": "MUN-097", "name": "Rómulo Gallegos", "state_code": "ST-008"},
        {"municipality_code": "MUN-098", "name": "San Carlos", "state_code": "ST-008"},
        {"municipality_code": "MUN-099", "name": "Tinaco", "state_code": "ST-008"},
        {"municipality_code": "MUN-100", "name": "Antonio Díaz", "state_code": "ST-009"},
        {"municipality_code": "MUN-101", "name": "Casacoima", "state_code": "ST-009"},
        {"municipality_code": "MUN-102", "name": "Pedernales", "state_code": "ST-009"},
        {"municipality_code": "MUN-103", "name": "Tucupita", "state_code": "ST-009"},
        {"municipality_code": "MUN-104", "name": "Acosta", "state_code": "ST-010"},
        {"municipality_code": "MUN-105", "name": "Bolívar", "state_code": "ST-010"},
        {"municipality_code": "MUN-106", "name": "Buchivacoa", "state_code": "ST-010"},
        {"municipality_code": "MUN-107", "name": "Cacique Manaure", "state_code": "ST-010"},
        {"municipality_code": "MUN-108", "name": "Carirubana", "state_code": "ST-010"},
        {"municipality_code": "MUN-109", "name": "Colina", "state_code": "ST-010"},
        {"municipality_code": "MUN-110", "name": "Dabajuro", "state_code": "ST-010"},
        {"municipality_code": "MUN-111", "name": "Democracia", "state_code": "ST-010"},
        {"municipality_code": "MUN-112", "name": "Falcón", "state_code": "ST-010"},
        {"municipality_code": "MUN-113", "name": "Federación", "state_code": "ST-010"},
        {"municipality_code": "MUN-114", "name": "Jacura", "state_code": "ST-010"},
        {"municipality_code": "MUN-115", "name": "José Laurencio Silva", "state_code": "ST-010"},
        {"municipality_code": "MUN-116", "name": "Los Taques", "state_code": "ST-010"},
        {"municipality_code": "MUN-117", "name": "Mauroa", "state_code": "ST-010"},
        {"municipality_code": "MUN-118", "name": "Miranda", "state_code": "ST-010"},
        {"municipality_code": "MUN-119", "name": "Monseñor Iturriza", "state_code": "ST-010"},
        {"municipality_code": "MUN-120", "name": "Palmasola", "state_code": "ST-010"},
        {"municipality_code": "MUN-121", "name": "Petit", "state_code": "ST-010"},
        {"municipality_code": "MUN-122", "name": "Píritu", "state_code": "ST-010"},
        {"municipality_code": "MUN-123", "name": "San Francisco", "state_code": "ST-010"},
        {"municipality_code": "MUN-124", "name": "Sucre", "state_code": "ST-010"},
        {"municipality_code": "MUN-125", "name": "Tocópero", "state_code": "ST-010"},
        {"municipality_code": "MUN-126", "name": "Unión", "state_code": "ST-010"},
        {"municipality_code": "MUN-127", "name": "Urumaco", "state_code": "ST-010"},
        {"municipality_code": "MUN-128", "name": "Zamora", "state_code": "ST-010"},
        {"municipality_code": "MUN-129", "name": "Camaguán", "state_code": "ST-011"},
        {"municipality_code": "MUN-130", "name": "Chaguaramas", "state_code": "ST-011"},
        {"municipality_code": "MUN-131", "name": "El Socorro", "state_code": "ST-011"},
        {"municipality_code": "MUN-132", "name": "José Félix Ribas", "state_code": "ST-011"},
        {"municipality_code": "MUN-133", "name": "José Tadeo Monagas", "state_code": "ST-011"},
        {"municipality_code": "MUN-134", "name": "Juan Germán Roscio", "state_code": "ST-011"},
        {"municipality_code": "MUN-135", "name": "Julián Mellado", "state_code": "ST-011"},
        {"municipality_code": "MUN-136", "name": "Las Mercedes", "state_code": "ST-011"},
        {"municipality_code": "MUN-137", "name": "Leonardo Infante", "state_code": "ST-011"},
        {"municipality_code": "MUN-138", "name": "Pedro Zaraza", "state_code": "ST-011"},
        {"municipality_code": "MUN-139", "name": "Ortíz", "state_code": "ST-011"},
        {"municipality_code": "MUN-140", "name": "San Gerónimo de Guayabal", "state_code": "ST-011"},
        {"municipality_code": "MUN-141", "name": "San José de Guaribe", "state_code": "ST-011"},
        {"municipality_code": "MUN-142", "name": "Santa María de Ipire", "state_code": "ST-011"},
        {"municipality_code": "MUN-143", "name": "Sebastián Francisco de Miranda", "state_code": "ST-011"},
        {"municipality_code": "MUN-144", "name": "Andrés Eloy Blanco", "state_code": "ST-012"},
        {"municipality_code": "MUN-145", "name": "Crespo", "state_code": "ST-012"},
        {"municipality_code": "MUN-146", "name": "Iribarren", "state_code": "ST-012"},
        {"municipality_code": "MUN-147", "name": "Jiménez", "state_code": "ST-012"},
        {"municipality_code": "MUN-148", "name": "Morán", "state_code": "ST-012"},
        {"municipality_code": "MUN-149", "name": "Palavecino", "state_code": "ST-012"},
        {"municipality_code": "MUN-150", "name": "Simón Planas", "state_code": "ST-012"},
        {"municipality_code": "MUN-151", "name": "Torres", "state_code": "ST-012"},
        {"municipality_code": "MUN-152", "name": "Urdaneta", "state_code": "ST-012"},
        {"municipality_code": "MUN-179", "name": "Alberto Adriani", "state_code": "ST-013"},
        {"municipality_code": "MUN-180", "name": "Andrés Bello", "state_code": "ST-013"},
        {"municipality_code": "MUN-181", "name": "Antonio Pinto Salinas", "state_code": "ST-013"},
        {"municipality_code": "MUN-182", "name": "Aricagua", "state_code": "ST-013"},
        {"municipality_code": "MUN-183", "name": "Arzobispo Chacón", "state_code": "ST-013"},
        {"municipality_code": "MUN-184", "name": "Campo Elías", "state_code": "ST-013"},
        {"municipality_code": "MUN-185", "name": "Caracciolo Parra Olmedo", "state_code": "ST-013"},
        {"municipality_code": "MUN-186", "name": "Cardenal Quintero", "state_code": "ST-013"},
        {"municipality_code": "MUN-187", "name": "Guaraque", "state_code": "ST-013"},
        {"municipality_code": "MUN-188", "name": "Julio César Salas", "state_code": "ST-013"},
        {"municipality_code": "MUN-189", "name": "Justo Briceño", "state_code": "ST-013"},
        {"municipality_code": "MUN-190", "name": "Libertador", "state_code": "ST-013"},
        {"municipality_code": "MUN-191", "name": "Miranda", "state_code": "ST-013"},
        {"municipality_code": "MUN-192", "name": "Obispo Ramos de Lora", "state_code": "ST-013"},
        {"municipality_code": "MUN-193", "name": "Padre Noguera", "state_code": "ST-013"},
        {"municipality_code": "MUN-194", "name": "Pueblo Llano", "state_code": "ST-013"},
        {"municipality_code": "MUN-195", "name": "Rangel", "state_code": "ST-013"},
        {"municipality_code": "MUN-196", "name": "Rivas Dávila", "state_code": "ST-013"},
        {"municipality_code": "MUN-197", "name": "Santos Marquina", "state_code": "ST-013"},
        {"municipality_code": "MUN-198", "name": "Sucre", "state_code": "ST-013"},
        {"municipality_code": "MUN-199", "name": "Tovar", "state_code": "ST-013"},
        {"municipality_code": "MUN-200", "name": "Tulio Febres Cordero", "state_code": "ST-013"},
        {"municipality_code": "MUN-201", "name": "Zea", "state_code": "ST-013"},
        {"municipality_code": "MUN-223", "name": "Acevedo", "state_code": "ST-014"},
        {"municipality_code": "MUN-224", "name": "Andrés Bello", "state_code": "ST-014"},
        {"municipality_code": "MUN-225", "name": "Baruta", "state_code": "ST-014"},
        {"municipality_code": "MUN-226", "name": "Brión", "state_code": "ST-014"},
        {"municipality_code": "MUN-227", "name": "Buroz", "state_code": "ST-014"},
        {"municipality_code": "MUN-228", "name": "Carrizal", "state_code": "ST-014"},
        {"municipality_code": "MUN-229", "name": "Chacao", "state_code": "ST-014"},
        {"municipality_code": "MUN-230", "name": "Cristóbal Rojas", "state_code": "ST-014"},
        {"municipality_code": "MUN-231", "name": "El Hatillo", "state_code": "ST-014"},
        {"municipality_code": "MUN-232", "name": "Guaicaipuro", "state_code": "ST-014"},
        {"municipality_code": "MUN-233", "name": "Independencia", "state_code": "ST-014"},
        {"municipality_code": "MUN-234", "name": "Lander", "state_code": "ST-014"},
        {"municipality_code": "MUN-235", "name": "Los Salias", "state_code": "ST-014"},
        {"municipality_code": "MUN-236", "name": "Páez", "state_code": "ST-014"},
        {"municipality_code": "MUN-237", "name": "Paz Castillo", "state_code": "ST-014"},
        {"municipality_code": "MUN-238", "name": "Pedro Gual", "state_code": "ST-014"},
        {"municipality_code": "MUN-239", "name": "Plaza", "state_code": "ST-014"},
        {"municipality_code": "MUN-240", "name": "Simón Bolívar", "state_code": "ST-014"},
        {"municipality_code": "MUN-241", "name": "Sucre", "state_code": "ST-014"},
        {"municipality_code": "MUN-242", "name": "Urdaneta", "state_code": "ST-014"},
        {"municipality_code": "MUN-243", "name": "Zamora", "state_code": "ST-014"},
        {"municipality_code": "MUN-258", "name": "Acosta", "state_code": "ST-015"},
        {"municipality_code": "MUN-259", "name": "Aguasay", "state_code": "ST-015"},
        {"municipality_code": "MUN-260", "name": "Bolívar", "state_code": "ST-015"},
        {"municipality_code": "MUN-261", "name": "Caripe", "state_code": "ST-015"},
        {"municipality_code": "MUN-262", "name": "Cedeño", "state_code": "ST-015"},
        {"municipality_code": "MUN-263", "name": "Ezequiel Zamora", "state_code": "ST-015"},
        {"municipality_code": "MUN-264", "name": "Libertador", "state_code": "ST-015"},
        {"municipality_code": "MUN-265", "name": "Maturín", "state_code": "ST-015"},
        {"municipality_code": "MUN-266", "name": "Piar", "state_code": "ST-015"},
        {"municipality_code": "MUN-267", "name": "Punceres", "state_code": "ST-015"},
        {"municipality_code": "MUN-268", "name": "Santa Bárbara", "state_code": "ST-015"},
        {"municipality_code": "MUN-269", "name": "Sotillo", "state_code": "ST-015"},
        {"municipality_code": "MUN-270", "name": "Uracoa", "state_code": "ST-015"},
        {"municipality_code": "MUN-271", "name": "Antolín del Campo", "state_code": "ST-016"},
        {"municipality_code": "MUN-272", "name": "Arismendi", "state_code": "ST-016"},
        {"municipality_code": "MUN-273", "name": "García", "state_code": "ST-016"},
        {"municipality_code": "MUN-274", "name": "Gómez", "state_code": "ST-016"},
        {"municipality_code": "MUN-275", "name": "Maneiro", "state_code": "ST-016"},
        {"municipality_code": "MUN-276", "name": "Marcano", "state_code": "ST-016"},
        {"municipality_code": "MUN-277", "name": "Mariño", "state_code": "ST-016"},
        {"municipality_code": "MUN-278", "name": "Península de Macanao", "state_code": "ST-016"},
        {"municipality_code": "MUN-279", "name": "Tubores", "state_code": "ST-016"},
        {"municipality_code": "MUN-280", "name": "Villalba", "state_code": "ST-016"},
        {"municipality_code": "MUN-281", "name": "Díaz", "state_code": "ST-016"},
        {"municipality_code": "MUN-282", "name": "Agua Blanca", "state_code": "ST-017"},
        {"municipality_code": "MUN-283", "name": "Araure", "state_code": "ST-017"},
        {"municipality_code": "MUN-284", "name": "Esteller", "state_code": "ST-017"},
        {"municipality_code": "MUN-285", "name": "Guanare", "state_code": "ST-017"},
        {"municipality_code": "MUN-286", "name": "Guanarito", "state_code": "ST-017"},
        {"municipality_code": "MUN-287", "name": "Monseñor José Vicente de Unda", "state_code": "ST-017"},
        {"municipality_code": "MUN-288", "name": "Ospino", "state_code": "ST-017"},
        {"municipality_code": "MUN-289", "name": "Páez", "state_code": "ST-017"},
        {"municipality_code": "MUN-290", "name": "Papelón", "state_code": "ST-017"},
        {"municipality_code": "MUN-291", "name": "San Genaro de Boconoíto", "state_code": "ST-017"},
        {"municipality_code": "MUN-292", "name": "San Rafael de Onoto", "state_code": "ST-017"},
        {"municipality_code": "MUN-293", "name": "Santa Rosalía", "state_code": "ST-017"},
        {"municipality_code": "MUN-294", "name": "Sucre", "state_code": "ST-017"},
        {"municipality_code": "MUN-295", "name": "Turén", "state_code": "ST-017"},
        {"municipality_code": "MUN-296", "name": "Andrés Eloy Blanco", "state_code": "ST-018"},
        {"municipality_code": "MUN-297", "name": "Andrés Mata", "state_code": "ST-018"},
        {"municipality_code": "MUN-298", "name": "Arismendi", "state_code": "ST-018"},
        {"municipality_code": "MUN-299", "name": "Benítez", "state_code": "ST-018"},
        {"municipality_code": "MUN-300", "name": "Bermúdez", "state_code": "ST-018"},
        {"municipality_code": "MUN-301", "name": "Bolívar", "state_code": "ST-018"},
        {"municipality_code": "MUN-302", "name": "Cajigal", "state_code": "ST-018"},
        {"municipality_code": "MUN-303", "name": "Cruz Salmerón Acosta", "state_code": "ST-018"},
        {"municipality_code": "MUN-304", "name": "Libertador", "state_code": "ST-018"},
        {"municipality_code": "MUN-305", "name": "Mariño", "state_code": "ST-018"},
        {"municipality_code": "MUN-306", "name": "Mejía", "state_code": "ST-018"},
        {"municipality_code": "MUN-307", "name": "Montes", "state_code": "ST-018"},
        {"municipality_code": "MUN-308", "name": "Ribero", "state_code": "ST-018"},
        {"municipality_code": "MUN-309", "name": "Sucre", "state_code": "ST-018"},
        {"municipality_code": "MUN-310", "name": "Valdéz", "state_code": "ST-018"},
        {"municipality_code": "MUN-341", "name": "Andrés Bello", "state_code": "ST-019"},
        {"municipality_code": "MUN-342", "name": "Antonio Rómulo Costa", "state_code": "ST-019"},
        {"municipality_code": "MUN-343", "name": "Ayacucho", "state_code": "ST-019"},
        {"municipality_code": "MUN-344", "name": "Bolívar", "state_code": "ST-019"},
        {"municipality_code": "MUN-345", "name": "Cárdenas", "state_code": "ST-019"},
        {"municipality_code": "MUN-346", "name": "Córdoba", "state_code": "ST-019"},
        {"municipality_code": "MUN-347", "name": "Fernández Feo", "state_code": "ST-019"},
        {"municipality_code": "MUN-348", "name": "Francisco de Miranda", "state_code": "ST-019"},
        {"municipality_code": "MUN-349", "name": "García de Hevia", "state_code": "ST-019"},
        {"municipality_code": "MUN-350", "name": "Guásimos", "state_code": "ST-019"},
        {"municipality_code": "MUN-351", "name": "Independencia", "state_code": "ST-019"},
        {"municipality_code": "MUN-352", "name": "Jáuregui", "state_code": "ST-019"},
        {"municipality_code": "MUN-353", "name": "José María Vargas", "state_code": "ST-019"},
        {"municipality_code": "MUN-354", "name": "Junín", "state_code": "ST-019"},
        {"municipality_code": "MUN-355", "name": "Libertad", "state_code": "ST-019"},
        {"municipality_code": "MUN-356", "name": "Libertador", "state_code": "ST-019"},
        {"municipality_code": "MUN-357", "name": "Lobatera", "state_code": "ST-019"},
        {"municipality_code": "MUN-358", "name": "Michelena", "state_code": "ST-019"},
        {"municipality_code": "MUN-359", "name": "Panamericano", "state_code": "ST-019"},
        {"municipality_code": "MUN-360", "name": "Pedro María Ureña", "state_code": "ST-019"},
        {"municipality_code": "MUN-361", "name": "Rafael Urdaneta", "state_code": "ST-019"},
        {"municipality_code": "MUN-362", "name": "Samuel Darío Maldonado", "state_code": "ST-019"},
        {"municipality_code": "MUN-363", "name": "San Cristóbal", "state_code": "ST-019"},
        {"municipality_code": "MUN-364", "name": "Seboruco", "state_code": "ST-019"},
        {"municipality_code": "MUN-365", "name": "Simón Rodríguez", "state_code": "ST-019"},
        {"municipality_code": "MUN-366", "name": "Sucre", "state_code": "ST-019"},
        {"municipality_code": "MUN-367", "name": "Torbes", "state_code": "ST-019"},
        {"municipality_code": "MUN-368", "name": "Uribante", "state_code": "ST-019"},
        {"municipality_code": "MUN-369", "name": "San Judas Tadeo", "state_code": "ST-019"},
        {"municipality_code": "MUN-370", "name": "Andrés Bello", "state_code": "ST-020"},
        {"municipality_code": "MUN-371", "name": "Boconó", "state_code": "ST-020"},
        {"municipality_code": "MUN-372", "name": "Bolívar", "state_code": "ST-020"},
        {"municipality_code": "MUN-373", "name": "Candelaria", "state_code": "ST-020"},
        {"municipality_code": "MUN-374", "name": "Carache", "state_code": "ST-020"},
        {"municipality_code": "MUN-375", "name": "Escuque", "state_code": "ST-020"},
        {"municipality_code": "MUN-376", "name": "José Felipe Márquez Cañizalez", "state_code": "ST-020"},
        {"municipality_code": "MUN-377", "name": "Juan Vicente Campos Elías", "state_code": "ST-020"},
        {"municipality_code": "MUN-378", "name": "La Ceiba", "state_code": "ST-020"},
        {"municipality_code": "MUN-379", "name": "Miranda", "state_code": "ST-020"},
        {"municipality_code": "MUN-380", "name": "Monte Carmelo", "state_code": "ST-020"},
        {"municipality_code": "MUN-381", "name": "Motatán", "state_code": "ST-020"},
        {"municipality_code": "MUN-382", "name": "Pampán", "state_code": "ST-020"},
        {"municipality_code": "MUN-383", "name": "Pampanito", "state_code": "ST-020"},
        {"municipality_code": "MUN-384", "name": "Rafael Rangel", "state_code": "ST-020"},
        {"municipality_code": "MUN-385", "name": "San Rafael de Carvajal", "state_code": "ST-020"},
        {"municipality_code": "MUN-386", "name": "Sucre", "state_code": "ST-020"},
        {"municipality_code": "MUN-387", "name": "Trujillo", "state_code": "ST-020"},
        {"municipality_code": "MUN-388", "name": "Urdaneta", "state_code": "ST-020"},
        {"municipality_code": "MUN-389", "name": "Valera", "state_code": "ST-020"},
        {"municipality_code": "MUN-390", "name": "Vargas", "state_code": "ST-021"},
        {"municipality_code": "MUN-391", "name": "Arístides Bastidas", "state_code": "ST-022"},
        {"municipality_code": "MUN-392", "name": "Bolívar", "state_code": "ST-022"},
        {"municipality_code": "MUN-407", "name": "Bruzual", "state_code": "ST-022"},
        {"municipality_code": "MUN-408", "name": "Cocorote", "state_code": "ST-022"},
        {"municipality_code": "MUN-409", "name": "Independencia", "state_code": "ST-022"},
        {"municipality_code": "MUN-410", "name": "José Antonio Páez", "state_code": "ST-022"},
        {"municipality_code": "MUN-411", "name": "La Trinidad", "state_code": "ST-022"},
        {"municipality_code": "MUN-412", "name": "Manuel Monge", "state_code": "ST-022"},
        {"municipality_code": "MUN-413", "name": "Nirgua", "state_code": "ST-022"},
        {"municipality_code": "MUN-414", "name": "Peña", "state_code": "ST-022"},
        {"municipality_code": "MUN-415", "name": "San Felipe", "state_code": "ST-022"},
        {"municipality_code": "MUN-416", "name": "Sucre", "state_code": "ST-022"},
        {"municipality_code": "MUN-417", "name": "Urachiche", "state_code": "ST-022"},
        {"municipality_code": "MUN-418", "name": "José Joaquín Veroes", "state_code": "ST-022"},
        {"municipality_code": "MUN-441", "name": "Almirante Padilla", "state_code": "ST-023"},
        {"municipality_code": "MUN-442", "name": "Baralt", "state_code": "ST-023"},
        {"municipality_code": "MUN-443", "name": "Cabimas", "state_code": "ST-023"},
        {"municipality_code": "MUN-444", "name": "Catatumbo", "state_code": "ST-023"},
        {"municipality_code": "MUN-445", "name": "Colón", "state_code": "ST-023"},
        {"municipality_code": "MUN-446", "name": "Francisco Javier Pulgar", "state_code": "ST-023"},
        {"municipality_code": "MUN-447", "name": "Páez", "state_code": "ST-023"},
        {"municipality_code": "MUN-448", "name": "Jesús Enrique Losada", "state_code": "ST-023"},
        {"municipality_code": "MUN-449", "name": "Jesús María Semprún", "state_code": "ST-023"},
        {"municipality_code": "MUN-450", "name": "La Cañada de Urdaneta", "state_code": "ST-023"},
        {"municipality_code": "MUN-451", "name": "Lagunillas", "state_code": "ST-023"},
        {"municipality_code": "MUN-452", "name": "Machiques de Perijá", "state_code": "ST-023"},
        {"municipality_code": "MUN-453", "name": "Mara", "state_code": "ST-023"},
        {"municipality_code": "MUN-454", "name": "Maracaibo", "state_code": "ST-023"},
        {"municipality_code": "MUN-455", "name": "Miranda", "state_code": "ST-023"},
        {"municipality_code": "MUN-456", "name": "Rosario de Perijá", "state_code": "ST-023"},
        {"municipality_code": "MUN-457", "name": "San Francisco", "state_code": "ST-023"},
        {"municipality_code": "MUN-458", "name": "Santa Rita", "state_code": "ST-023"},
        {"municipality_code": "MUN-459", "name": "Simón Bolívar", "state_code": "ST-023"},
        {"municipality_code": "MUN-460", "name": "Sucre", "state_code": "ST-023"},
        {"municipality_code": "MUN-461", "name": "Valmore Rodríguez", "state_code": "ST-023"},
        {"municipality_code": "MUN-462", "name": "Libertador", "state_code": "ST-024"}
    ]

    for data in municipalities:
        state_code = data.pop("state_code")
        state = State.query.filter_by(state_code=state_code).first()
        
        if not state:
            print(f"Error: No se encontró State con código '{state_code}'. Ejecuta seed_states primero.")
            return

        data["state_id"] = state.id
        municipality = Municipality(**data)
        db.session.add(municipality)
    
    db.session.commit()
    print("Municipalities seeded successfully.")
