"""Migración sages

Revision ID: 3acc7b7bbf8a
Revises: 
Create Date: 2026-07-08 18:04:39.968980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3acc7b7bbf8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('identification_type', sa.String(length=50), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('rif'),
    schema='sages'
    )
    op.create_table('educational_levels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_code'),
    schema='sages'
    )
    op.create_table('institution_dependencies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dependency_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dependency_code'),
    schema='sages'
    )
    op.create_table('institution_scopes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_code'),
    schema='sages'
    )
    op.create_table('institution_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('institution_type_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_type_code'),
    schema='sages'
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('view', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code'),
    schema='sages'
    )
    op.create_table('persons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_code', sa.String(length=50), nullable=False),
    sa.Column('identification_type', sa.String(length=50), nullable=False),
    sa.Column('identification_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identification_number'),
    sa.UniqueConstraint('person_code'),
    schema='sages'
    )
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('position_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_code'),
    schema='sages'
    )
    op.create_table('reasons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason_code'),
    schema='sages'
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code'),
    schema='sages'
    )
    op.create_table('states',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code'),
    schema='sages'
    )
    op.create_table('status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code'),
    schema='sages'
    )
    op.create_table('training_categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code'),
    schema='sages'
    )
    op.create_table('cities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('city_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_capital', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['sages.states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_code'),
    schema='sages'
    )
    op.create_table('municipalities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('municipality_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['sages.states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_code'),
    schema='sages'
    )
    op.create_table('permission_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sages.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sages.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('trainings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('training_category_id', sa.BigInteger(), nullable=False),
    sa.Column('training_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['sages.status.id'], ),
    sa.ForeignKeyConstraint(['training_category_id'], ['sages.training_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_code'),
    schema='sages'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_code', sa.String(length=50), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['sages.persons.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sages.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code'),
    schema='sages'
    )
    op.create_table('binnacle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sages.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('parishes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('municipality_id', sa.BigInteger(), nullable=False),
    sa.Column('parish_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['sages.municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parish_code'),
    schema='sages'
    )
    op.create_table('role_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sages.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sages.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('state_trainings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['sages.states.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['sages.trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('training_levels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=False),
    sa.Column('educational_level_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['educational_level_id'], ['sages.educational_levels.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['sages.trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('institutions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('institution_code', sa.String(length=50), nullable=False),
    sa.Column('institution_type_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('plantel_code', sa.String(length=50), nullable=False),
    sa.Column('institution_scope_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_dependency_id', sa.BigInteger(), nullable=False),
    sa.Column('parish_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_dependency_id'], ['sages.institution_dependencies.id'], ),
    sa.ForeignKeyConstraint(['institution_scope_id'], ['sages.institution_scopes.id'], ),
    sa.ForeignKeyConstraint(['institution_type_id'], ['sages.institution_types.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['sages.parishes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sages.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_code'),
    sa.UniqueConstraint('plantel_code'),
    schema='sages'
    )
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('parish_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['sages.cities.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['sages.parishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'parish_id', name='unique_coverage'),
    schema='sages'
    )
    op.create_table('places',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_code', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parish_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['sages.companies.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['sages.parishes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sages.status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_code'),
    schema='sages'
    )
    op.create_table('company_staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['sages.persons.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['sages.places.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['sages.positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('institution_levels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('educational_level_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['educational_level_id'], ['sages.educational_levels.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['sages.institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('institutional_staff',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=False),
    sa.Column('institution_id', sa.BigInteger(), nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['sages.institutions.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['sages.persons.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['sages.positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('institutional_staff_id', sa.BigInteger(), nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('historical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institutional_staff_id'], ['sages.institutional_staff.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sages.status.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['sages.trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_code'),
    schema='sages'
    )
    op.create_table('evidences',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sages.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('ratings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sages.requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sages.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('request_justifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('reason_id', sa.BigInteger(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reason_id'], ['sages.reasons.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['sages.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('request_plannings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requests_id', sa.BigInteger(), nullable=False),
    sa.Column('acceptance_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_for', sa.Date(), nullable=True),
    sa.Column('execution_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_exceeded', sa.Boolean(), nullable=False),
    sa.Column('time_exceeded', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requests_id'], ['sages.requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    op.create_table('request_trackings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['sages.requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sages.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sages'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_trackings', schema='sages')
    op.drop_table('request_plannings', schema='sages')
    op.drop_table('request_justifications', schema='sages')
    op.drop_table('ratings', schema='sages')
    op.drop_table('evidences', schema='sages')
    op.drop_table('requests', schema='sages')
    op.drop_table('institutional_staff', schema='sages')
    op.drop_table('institution_levels', schema='sages')
    op.drop_table('company_staff', schema='sages')
    op.drop_table('places', schema='sages')
    op.drop_table('locations', schema='sages')
    op.drop_table('institutions', schema='sages')
    op.drop_table('training_levels', schema='sages')
    op.drop_table('state_trainings', schema='sages')
    op.drop_table('role_users', schema='sages')
    op.drop_table('parishes', schema='sages')
    op.drop_table('binnacle', schema='sages')
    op.drop_table('users', schema='sages')
    op.drop_table('trainings', schema='sages')
    op.drop_table('permission_roles', schema='sages')
    op.drop_table('municipalities', schema='sages')
    op.drop_table('cities', schema='sages')
    op.drop_table('training_categories', schema='sages')
    op.drop_table('status', schema='sages')
    op.drop_table('states', schema='sages')
    op.drop_table('roles', schema='sages')
    op.drop_table('reasons', schema='sages')
    op.drop_table('positions', schema='sages')
    op.drop_table('persons', schema='sages')
    op.drop_table('permissions', schema='sages')
    op.drop_table('institution_types', schema='sages')
    op.drop_table('institution_scopes', schema='sages')
    op.drop_table('institution_dependencies', schema='sages')
    op.drop_table('educational_levels', schema='sages')
    op.drop_table('companies', schema='sages')
    # ### end Alembic commands ###
