from enum import Enum

class AuditModule(str, Enum):
    AUTH = 'Inicio de sesión' 
    USERS = 'Usuarios'
    INSTITUTIONS = 'Instituciones'
    TRAININGS = 'Formación' 
    REQUESTS = 'Solicitudes' 
    CONFIGURATIONS = 'Configuraciones'
    PRE_REGISTRATION = 'Pre-Registro'
    SERVICES = 'Servicios'

class AuditAction(str, Enum):
    # Acciones Existentes (No tocar para mantener retrocompatibilidad)
    LOGIN_EXITOSO = 'LOGIN_EXITOSO'
    LOGIN_FALLIDO = 'LOGIN_FALLIDO'
    LOGOUT = 'LOGOUT'
    RECUPERACION_SOLICITADA = 'RECUPERACION_SOLICITADA'
    CODIGO_VERIFICADO_EXITOSO = 'CODIGO_VERIFICADO_EXITOSO'
    CODIGO_VERIFICADO_FALLIDO = 'CODIGO_VERIFICADO_FALLIDO'
    CAMBIO_CONTRASENA_RECUPERACION = 'CAMBIO_CONTRASENA_RECUPERACION'
    CANCELACION_RECUPERACION = 'CANCELACION_RECUPERACION'
    CAMBIO_PASSWORD = 'CAMBIO_PASSWORD'
    CAMBIO_ESTATUS = 'CAMBIO_ESTATUS'
    ACTUALIZAR = 'ACTUALIZAR'
    REGISTRO_NUEVO = 'REGISTRO_NUEVO'
    CONSULTA_DETALLE = 'CONSULTA_DETALLE'
    CARGAR_EVIDENCIA = 'CARGAR_EVIDENCIA'
    INVITACION_ENVIADA = 'INVITACION_ENVIADA'
    DESCARGA_REGISTRO = 'DESCARGA_REGISTRO'
    
    # Nuevas Acciones (auditorias.md)
    # Seguridad
    CODIGO_VERIFICADO = 'CODIGO_VERIFICADO'
    ACTIVACION_CUENTA = 'ACTIVACION_CUENTA'
    ACTIVACION_TOKEN_INVALIDO = 'ACTIVACION_TOKEN_INVALIDO'
    
    # Usuarios
    REGISTRO_ADMIN_INTERNO = 'REGISTRO_ADMIN_INTERNO'
    APROBACION_SOLICITUD_REGISTRO = 'APROBACION_SOLICITUD_REGISTRO'
    RECHAZO_SOLICITUD_REGISTRO = 'RECHAZO_SOLICITUD_REGISTRO'
    CAMBIO_ESTATUS_USUARIO = 'CAMBIO_ESTATUS_USUARIO'
    ACTUALIZAR_USUARIO_ADMIN = 'ACTUALIZAR_USUARIO_ADMIN'
    ACTUALIZAR_CONTACTO_PROPIO = 'ACTUALIZAR_CONTACTO_PROPIO'
    CAMBIO_PASSWORD_PERFIL = 'CAMBIO_PASSWORD_PERFIL'
    CONSULTA_EVIDENCIA = 'CONSULTA_EVIDENCIA'
    
    # Pre-Registro
    SOLICITUD_NUEVA_INSTITUCION = 'SOLICITUD_NUEVA_INSTITUCION'
    SOLICITUD_VINCULACION_EXISTENTE = 'SOLICITUD_VINCULACION_EXISTENTE'
    SOLICITUD_DELEGADA_INVITACION = 'SOLICITUD_DELEGADA_INVITACION'
    
    # Instituciones
    ACTUALIZAR_INFRAESTRUCTURA = 'ACTUALIZAR_INFRAESTRUCTURA'
    CAMBIO_ESTATUS_INSTITUCION = 'CAMBIO_ESTATUS_INSTITUCION'
    INVITACION_COLABORADOR = 'INVITACION_COLABORADOR'

class AuditStatus(str, Enum):
    EXITOSO = 'EXITOSO'
    FALLIDO = 'FALLIDO'
    COMPLETADO = 'COMPLETADO'
    MODIFICADO = 'MODIFICADO'
    RECIBIDO = 'RECIBIDO'
    EN_PROCESO = 'EN_PROCESO'
    RECHAZADO = 'RECHAZADO'